### PR TITLE
CORE-5057 add Jenkins job for Snyk CLI scan

### PR DESCRIPTION
**Pull request by ronanbrowne**
Add nightly job to run Snyk CLI scan for vulnerability detection

 Tested [here](https://ci02.dev.r3.com/job/Corda5/job/Snyk-Scans/job/corda-gradle-plugins-snyk-scan/job/CORE-5057%252Fadd-snyk/)

### CODE REVIEW

**Review by chrisr3 — COMMENTED** [review]
Well, my first rather obvious question is "What does this _do_?" :thinking:

**Comment by ronanbrowne** [comment]
> Well, my first rather obvious question is "What does this _do_?" 🤔

Accompanying logic [here ](https://github.com/corda/corda-shared-build-pipeline-steps/blob/5.0/vars/cordaSnykScanPipeline.groovy) which this invokes .

Snyk is our new security tooling of choice which will be replacing nexus as the "first line of defense" over the coming weeks as its rolled out. The pipeline linked, Uses Snyks CLI tool to do a scan of the code base , and send the results to our [snyk server](https://app.snyk.io/org/r3-corda-5/projects)  it also generates a HTML based report that you can see if you clck into the attached [build ](https://ci02.dev.r3.com/job/Corda5/job/Snyk-Scans/job/corda-gradle-plugins-snyk-scan/job/CORE-5057%252Fadd-snyk/1/) and scroll to the "SNYK Report Summary" section at the bottom of that page and follow the relevant links.

There will be more appropriate tech talk / knowledge share on this upcoming but just getting all the moving parts in place at the moment.

Note there is also a gradle [plugin ](https://github.com/snyk/gradle-plugin) that can be applied  which allows you to run ./gradlew snyk-test locally as part of your workflow or even hook this into the test task if so desired. This is just a wrapper for the CLI tool untimely.

**Comment by chrisr3** [comment]
Thanks, although I must point out that Gradle plugins written in Kotlin will always use Gradle's _own_ Kotlin libraries in practice. So there's not much point in Snyk complaining to _us_ about plugins using Kotlin 1.5.31.

**Review by chrisr3 — APPROVED** [review]
LGTM. (What's the worst that could happen? :shrug:)

**Pull request merged**
